### PR TITLE
Added ideas and updated makefile.

### PR DESCRIPTION
**Pull request by mgiannopoulos24**
I assume your project is based on [Kilo Text Editor](https://viewsourcecode.org/snaptoken/kilo/). 
I updated the README with a few ideas for you to implement and also made the Makefile a bit better. Now you can `make` and `make clean` to remove the executable.

### CODE REVIEW

**Comment by Filip-Nachov** [comment]
nice thank you

**Comment by Filip-Nachov** [comment]
oh and yes, it is cuz I am too dumb to be creative. So I thought about just doing it as the kilo one and then changing the things to make mine outstand from the kilo one (its really weird that you reconised it you are the first person to do so)

**Comment by mgiannopoulos24** [comment]
I recognized it because I made it as well (Implementation [here](https://github.com/mgiannopoulos24/Projects-C/blob/main/Project%20Ted%202/ted2.c)). And from whatever tutorial I've seen its the only one that has `EnableRawMode()`. [Build-your-own-xyz](https://github.com/codecrafters-io/build-your-own-x) has a lot of projects that you can try.

**Comment by Filip-Nachov** [comment]
yeah I use the project based learning repo and I liked this project it is really nice and easy to follow and learn from

**Pull request merged**
